Redo the way undocumented definitions are counted

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -69,11 +69,11 @@ jobs:
         # "missing documentation".
         - stack --no-terminal exec -- ghc-pkg unregister guide
         - stack --no-terminal build --test --no-run-tests --haddock --no-haddock-deps --haddock-arguments='--no-warnings' 2> haddock.log
-        - awk '/\(src\//' haddock.log | awk 'END { print NR }' > undocumented
-        - awk '{ print "undocumented == " $1 }' undocumented
+        - export uncodumented=$(awk '/\(src\// {count++} END{print count}' haddock.log)
+        - echo "Undocumented definitions: $undocumented"
         - |
-          if [[ `cat undocumented` -gt 251 ]]; then
-            >&2 echo "FAIL: found $(cat undocumented) top-level undocumented definitions. The current limit is 251. Please, add Haddock comments to undocumented definitions!"
+          if [ $undocumented -gt 251 ]; then
+            >&2 echo "FAIL: found $undocumented top-level undocumented definitions. The current limit is 251. Please, add Haddock comments to undocumented definitions!"
             exit 1
           fi
       before_cache:
