Add check equality in travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -98,6 +98,18 @@ jobs:
             >&2 echo "FAIL: found $undocumented top-level undocumented definitions. The current limit is 251. Please, add Haddock comments to undocumented definitions!"
             exit 1
           fi
+        # Load AcidState to Postgres and check if they are equal
+        - docker run --name guide-db -e POSTGRES_PASSWORD=3 -e POSTGRES_DB=guide -p 5432:5432 -d postgres
+        - stack exec --cwd back -- guide load-into-postgres 2> postgres.log
+        - cat postgres.log
+        - export checkBase=$(awk '/True/ {count++} END{print count}' postgres.log)
+        - |
+          echo "AcidState == Postgres: $checkBase"
+        - |
+          if [ $checkBase -lt 4 ]; then
+            >&2 echo "FAIL: Postgres base is not equal to AcidState base."
+            exit 1
+          fi
       before_cache:
         - rm -rf $HOME/.stack/programs  #  GHC is faster to install than to cache
 
